### ISSUE TITLE
Handling of set_volume value

### ISSUE THREAD

**Issue by 1account** [corus87/kodi-neuron#2]
How does this translate to the code, especially for other languages? I would like to say "set volume 90%". 

I think steps 0, 10, 20, .. 100% are sufficient for this task.

**Comment by corus87** [comment]
Dont try to use the percentage at the end, just say "set volume to 90" because the volume needs to be an integer. Anyhow it was not working because I forgot to convert the string to an integer. 
I made a update, maybe you can give it a try?

**Comment by 1account** [comment]
i did not try to speak the percentage. can your code handle different languages without hardcoding stuff somehow? this language logic mapping should be done in the yml or in a template. thank you.

**Comment by corus87** [comment]
Ok we need a template for it, same problem like the repeat action. I will try to find a solution.

**Comment by 1account** [comment]
I will close this as you fixed the string to integer conversion and everything else is discussed in #1.
