### ISSUE TITLE
ModuleNotFoundError: No module named 'kodijson'

### ISSUE THREAD

**Issue by juanpa669** [corus87/kodi-neuron#6]
Hi Patrick,

It seems I've already have this error on Kodi neuron installation, but really don't remember how to fix it. So I create an issue to remember it next time :D 

I just run a new rapsbian install on Rpi 3 and a fresh kalliope install via bash script.
Then I ran the command to install Kodi neuron.

How can I fix it ?

Thanks ;) 

Edit: Just ran a pip3 install kodi-json
now got ModuleNotFoundError: No module named 'fuzzywuzzy', I will try to install it the same way

**Comment by corus87** [comment]
Hi @juanpa669,
with pip3 there is a new syntax we have to use to install multiple dependencies in the install.yml, it should be fixed now. 
Anyway thanks for the report :)
